# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Ollie & Clare

description: "Ollie & Clare: Design, Architecture, Hand-made, Websites"

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://ollieandclare.org" # the base hostname & protocol for your site

sass:
  style: compressed

# Portfolio

collections:
  architecture-portfolio:
    output: true
    permalink: /architecture/portfolio/:path/

defaults:
  - scope:
      path: ""
      type: architecture-portfolio
    values:
      layout: project
      section: Architecture Portfolio
      header-image: architecture
      header-image-position: btm


# Build settings
markdown: kramdown
